[package]
name = "walle-core"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Onebot Lib in Rust"
authors = ["Abrahum<307887491@qq.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
qq = []
http = ["hyper"]
websocket = ["tokio-tungstenite", "futures-util"]
app = ["dashmap"]
impl = ["uuid"]
full = ["qq", "http", "websocket", "app", "impl"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rmp-serde = "0.15"
async-trait = "0.1"
tracing = "0.1"
colored = "2"
dashmap = { version = "4.0", optional = true }
uuid = { version = "0.8", optional = true }
hyper = { version = "0.14", features = ["full"], optional = true }
tokio = { version = "1.0", features = ["sync", "net", "rt", "time", "macros"] }
tokio-tungstenite = { version = "0.15", optional = true }
futures-util = { version = "0.3", features = ["sink"], optional = true }

[workspace]
members = ["recruit", "mira", "walle-py", "walle-v11"]
