[package]
name = "walle-core"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Onebot Lib in Rust"
authors = ["Abrahum<307887491@qq.com>"]
homepage = "https://github.com/abrahum/Walle-core"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
http = ["hyper"]
websocket = ["tokio-tungstenite"]
app = []
impl = ["uuid"]
v11 = []
full = ["http", "websocket", "app", "impl"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rmp-serde = "1.0"
async-trait = "0.1"
tracing = "0.1"
colored = "2"
uuid = { version = "0.8", optional = true }
hyper = { version = "0.14", features = ["full"], optional = true }
tokio = { version = "1.0", features = ["sync", "net", "rt", "time", "macros"] }
tokio-tungstenite = { version = "0.15", optional = true }
futures-util = { version = "0.3", features = ["sink"] }
thiserror = "*"

[workspace]
members = ["mira", "walle-py", "walle-v11"]
