[package]
name = "walle-macro"
version = "0.7.0-a2"
edition = "2021"
license = "MIT"
authors = ["Abrahum<307887491@qq.com>"]
homepage = "https://github.com/abrahum/Walle-core"
description = "macro for walle-core"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = "1"
proc-macro2 = "1"
