[package]
name = "walle-py"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "walle_py"
crate-type = ["cdylib"]

[dependencies]
walle-core = { path = "../", features = ["full"] }
pyo3 = { version = "0.14.2", features = ["extension-module"] }
pyo3-asyncio = { version = "0.14", features = ["tokio-runtime", "attributes"] }
tokio = "1.4"
